# Generated by Django 6.0.7 on 2026-08-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Себестоимость на момент покупки', max_digits=10),
            preserve_default=False,
        ),
    ]
