# Generated by Django 6.0.7 on 2026-08-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='expares_at',
            new_name='expires_at',
        ),
    ]
